language: java
jdk: openjdk17

before_install:
  - echo "Alibaba&the80thieves$" | docker login -u "elpadriiiino" --password-stdin
  - docker pull openjdk:17-jre-slim-sid
script:
  - ./mvnw clean install
  - ./mvnw deploy jib:build -P deploy-docker